image:
  file: .gitpod.Dockerfile
# Command to start on workspace startup
tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: npm ci && cd frontend && npm ci && cd ../ && cp sample.env .env && npm run fill-db
    command: npm run dev
  - command: gp await-port 9000 && gp preview $(gp url 9000)/api
  - command: gp await-port 8080 && gp preview $(gp url 8080)
# Ports to expose on workspace startup
ports:
  - port: 9000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.0:M3Ww4EayZWhGCgk49C1Ldw==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==

github:
  prebuilds:
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
