image:
  file: .gitpod.Dockerfile
# Command to start on workspace startup
tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: npm install
    command: cp sample.env .env && npm run fill-db && npm run dev
  - command: gp await-port 9000 && gp preview $(gp url 9000)/api
# Ports to expose on workspace startup
ports:
  - port: 9000
    onOpen: ignore

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.0:M3Ww4EayZWhGCgk49C1Ldw==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
